### ISSUE TITLE
Make the retry aspect Spring Boot 3 ready

### ISSUE THREAD

**Issue by ChrisSchoe** [viadee/external-task-retry-aspect#107]
Currently, the bean factory declaration of the aspect does not work with Spring Boot 3. 
Instead of having a spring.factories file, this information should now lie in a new file META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, cf. https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#auto-configuration-registration . 
As this behaviour works with Spring Boot 2.7 as well it would make the aspect Spring Boot 2 as well as Spring Boot 3 comptaible and allow people to easily use it in both settings :)

**Comment by ChrisSchoe** [comment]
I opened https://github.com/viadee/external-task-retry-aspect/pull/108 to address this problem.

**Comment by rnschk** [comment]
Tank you very much! 🙏
